const ADD_PRODUCT = 'ADD_PRODUCT';
const RESET_PRODUCTS = 'RESET_PRODUCTS';
const DELETE_PRODUCT = 'DELETE_PRODUCTS';
const TRANSLATE_NAMES = 'TRANSLATE_NAMES';

export default {
ADD_PRODUCT,
RESET_PRODUCTS,
DELETE_PRODUCT,
TRANSLATE_NAMES,
}