const ADD_PRODUCT = 'ADD_PRODUCT';
const RESET_PRODUCTS = 'RESET_PRODUCTS';
const DELETE_PRODUCT = 'DELETE_PRODUCTS';
const CHANGE_LANG = 'CHANGE_LANG';

export default {
ADD_PRODUCT,
RESET_PRODUCTS,
DELETE_PRODUCT,
CHANGE_LANG,
}